// flow-typed signature: 1a31dbf78a45d3f77ec13f488a3010cd
// flow-typed version: <<STUB>>/if-env_v^1.0.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'if-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'if-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'if-env/bin/if-env' {
  declare module.exports: any;
}

declare module 'if-env/test/if-env.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'if-env/bin/if-env.js' {
  declare module.exports: $Exports<'if-env/bin/if-env'>;
}
declare module 'if-env/test/if-env.test.js' {
  declare module.exports: $Exports<'if-env/test/if-env.test'>;
}
