// @flow

export const ATTEMPTING_LOGIN = 'ATTEMPTING_LOGIN';
export const ATTEMPTING_LOGOUT = 'ATTEMPTING_LOGOUT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOOUT';
export const ADD_CURRENT_USER = 'ADD_CURRENT_USER';
export const ADD_USERS = 'ADD_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const SET_ABOUT_PROFILE = 'SET_ABOUT_PROFILE';
export const ADD_FIREBASE_PROFILE_ABOUT_DATA = 'ADD_FIREBASE_PROFILE_ABOUT_DATA';
export const SET_HEADLINE_PROFILE = 'SET_HEADLINE_PROFILE';
export const ADD_FIREBASE_PROFILE_HEADLINE_DATA = 'ADD_FIREBASE_PROFILE_HEADLINE_DATA';
export const CLEAR_ABOUT_INPUT = 'CLEAR_ABOUT_INPUT';
export const CLEAR_PROFILE_INPUT = 'CLEAR_PROFILE_INPUT';
