// @flow

export const ATTEMPTING_LOGIN = 'ATTEMPTING_LOGIN';
export const ATTEMPTING_LOGOUT = 'ATTEMPTING_LOGOUT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOOUT';
export const ADD_USER = 'ADD_USER';
export const ADD_USERS = 'ADD_USERS';
export const SET_ABOUT_PROFILE = 'SET_ABOUT_PROFILE';
export const ADD_FIREBASE_PROFILE_ABOUT_DATA = 'ADD_FIREBASE_PROFILE_ABOUT_DATA';
export const CLEAR_INPUT = 'CLEAR_INPUT';
