// @flow

export const ATTEMPTING_LOGIN = 'ATTEMPTING_LOGIN';
export const ATTEMPTING_LOGOUT = 'ATTEMPTING_LOGOUT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOOUT';
export const ADD_CURRENT_USER = 'ADD_CURRENT_USER';
export const ADD_USERS = 'ADD_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const SET_ABOUT_PROFILE = 'SET_ABOUT_PROFILE';
export const ADD_FIREBASE_PROFILE_ABOUT_DATA = 'ADD_FIREBASE_PROFILE_ABOUT_DATA';
export const SET_HEADLINE_PROFILE = 'SET_HEADLINE_PROFILE';
export const ADD_FIREBASE_PROFILE_HEADLINE_DATA = 'ADD_FIREBASE_PROFILE_HEADLINE_DATA';
export const EDIT_PROFILE_IMAGE_URL = 'EDIT_PROFILE_IMAGE_URL';
export const ADD_SOCIAL_MEDIA_URLS = 'ADD_SOCIAL_MEDIA_URLS';
export const SET_SOCIAL_URL_INPUT_VALUES = 'SET_SOCIAL_URL_INPUT_VALUES';
export const SET_SOCIAL_URL_INPUT_VALUE = 'SET_SOCIAL_URL_INPUT_VALUE';
export const INIT_SOCIAL_URL_INPUT_VALUES = 'INIT_SOCIAL_URL_INPUT_VALUES';
export const INIT_SOCIAL_MEDIA_URLS = 'INIT_SOCIAL_MEDIA_URLS';
export const ADD_PROFILE = 'ADD_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
